import re
from pathlib import Path

# Mapping of roman urdu names to english + roman format
name_mapping = {
    # Vegetables
    'Palak': 'Spinach (Palak)',
    'Timatar': 'Tomato (Timatar)',
    'Alu': 'Potato (Alu)',
    'Hara Dhania': 'Coriander Leaves (Hara Dhania)',
    'Piyaz': 'Onion (Piyaz)',
    'Lehsan': 'Garlic (Lehsan)',
    'Adrak': 'Ginger (Adrak)',
    'Kheera': 'Cucumber (Kheera)',
    'Shimla Mirch': 'Capsicum (Shimla Mirch)',
    'Phool Gobi': 'Cauliflower (Phool Gobi)',
    'Baingan': 'Brinjal (Baingan)',
    'Karela': 'Bitter Gourd (Karela)',
    'Matar': 'Peas (Matar)',
    'Pudina': 'Mint (Pudina)',
    'Methi': 'Fenugreek Leaves (Methi)',
    'Tori': 'Zucchini (Tori)',
    'Bhindi': 'Lady Finger (Bhindi)',
    'Gajar': 'Carrot (Gajar)',
    'Mooli': 'Radish (Mooli)',
    'Kaddu': 'Pumpkin (Kaddu)',
    'Karafs': 'Celery (Karafs)',
    'Gandana': 'Leeks (Gandana)',
    'Shakarkandi': 'Sweet Potato (Shakarkandi)',
    'Shalgam': 'Turnip (Shalgam)',
    'Moringa/Suhanjna': 'Drumsticks (Moringa/Suhanjna)',
    'Hara Piyaz': 'Spring Onions (Hara Piyaz)',
    'Chukandar': 'Beetroot (Chukandar)',
    'Hari Gobi': 'Broccoli (Hari Gobi)',
    'Bhutta': 'Corn (Bhutta)',
    'Lauki': 'Bottle Gourd (Lauki)',
    'Arvi': 'Arvi (Arvi)',
    'Hari Mirch': 'Green Chillies (Hari Mirch)',
    'Bheen/Kamal Kakri': 'Lotus Root (Bheen/Kamal Kakri)',
    'Sabz Masale': 'Mixed Herb Pack (Sabz Masale)',
    'Bund Gobi': 'Cabbage (Bund Gobi)',
    'Matar Dana': 'Baby Peas (Matar Dana)',
    'Ajmood': 'Parsley (Ajmood)',
    'Asparagus': 'Asparagus (Asparagus)',
    'Khumb': 'Mushrooms (Khumb)',
    
    # Fruits
    'Kinnow': 'Kinnow (Kinnow)',
    'Aam': 'Mango (Aam)',
    'Kela': 'Banana (Kela)',
    'Toot Farangi': 'Strawberries (Toot Farangi)',
    'Kala Kulu': 'Apple (Kala Kulu)',
    'Amrood': 'Guava (Amrood)',
    'Anar': 'Pomegranate (Anar)',
    'Tarbuz': 'Watermelon (Tarbuz)',
    'Angoor': 'Grapes (Angoor)',
    'Kalay Angoor': 'Black Grapes (Kalay Angoor)',
    'Papita': 'Papaya (Papita)',
    'Nashpati': 'Pear (Nashpati)',
    'Aaru': 'Peach (Aaru)',
    'Aloo Bukhara': 'Plum (Aloo Bukhara)',
    'Khubani': 'Apricots (Khubani)',
    'Litchi': 'Lychee (Litchi)',
    'Narial': 'Coconut (Narial)',
    'Kharbooza': 'Melon (Kharbooza)',
    'Kamalam': 'Dragon Fruit (Kamalam)',
    'Ananas': 'Pineapple (Ananas)',
    'Kivi': 'Kiwi (Kivi)',
    'Cheri': 'Cherries (Cheri)',
    'Anjeer': 'Figs (Anjeer)',
    'Khajoor': 'Dates (Khajoor)',
    'Santra': 'Orange (Santra)',
    'Meetha/Nimbu': 'Lemon (Meetha/Nimbu)',
    'Malta': 'Malta (Malta)',
    'Jamun': 'Jamun (Jamun)',
    'Falsa': 'Falsa (Falsa)',
    'Sarda/Garma': 'Muskmelon (Sarda/Garma)',
    'Makkhan Phal': 'Avocado (Makkhan Phal)',
    'Krishna Phal': 'Passion Fruit (Krishna Phal)',
    'Imli': 'Tamarind (Imli)',
    'Shahtoot': 'Mulberry (Shahtoot)',
    'Kathal': 'Jackfruit (Kathal)',
    
    # Groceries
    'Chawal': 'Rice (Chawal)',
    'Desi Ghee Jar': 'Ghee (Desi)',
    'Anday': 'Eggs (Anday)',
    'Zaitoon ka Tail': 'Olive Oil (Zaitoon ka Tail)',
    'Chakki Atta': 'Flour (Chakki Atta)',
    'Cheeni': 'Sugar (Cheeni)',
    'Namak': 'Salt (Namak)',
    'Chai Patti': 'Tea (Chai Patti)',
    'Doodh': 'Milk (Doodh)',
    'Dahi': 'Yogurt (Dahi)',
    'Makkhan': 'Butter (Makkhan)',
    'Paneer': 'Cheese (Paneer)',
    'Masoor Dal': 'Red Lentils (Masoor Dal)',
    'Moong Dal': 'Moong Dal (Moong Dal)',
    'Kabuli Chana': 'Chickpeas (Kabuli Chana)',
    'Urad Dal': 'Urad Dal (Urad Dal)',
    'Canola Tail': 'Cooking Oil (Canola)',
    'Tamatar Paste Tin': 'Tomato Paste (Tamatar)',
    'Zeera': 'Cumin (Zeera)',
    'Sookha Dhania': 'Coriander Seeds (Sookha Dhania)',
    'Haldi Powder': 'Turmeric (Haldi)',
    'Lal Mirch': 'Red Chilli Powder (Lal Mirch)',
    'Garam Masala Blend': 'Garam Masala (Garam Masala)',
    'Special Biryani Masala': 'Biryani Masala (Biryani)',
    'Shehad': 'Honey (Shehad)',
    'Double Roti': 'Bread (Double Roti)',
    'Spaghetti Pasta': 'Pasta (Spaghetti)',
    'Daliya': 'Oats (Daliya)',
    'Corn Flakes': 'Corn Flakes (Corn)',
    'Zeera Biscuits': 'Biscuits (Zeera)',
    'Opa Matar': 'Peas (Opa)',
    'Opa Mix Sabzi': 'Mix Vegetables (Opa)',
}

path = Path('data/shop-catalog.ts')
text = path.read_text(encoding='utf-8')

# Replace all names
for roman, english_roman in name_mapping.items():
    pattern = f'name: "{roman}"'
    replacement = f'name: "{english_roman}"'
    text = text.replace(pattern, replacement)

path.write_text(text, encoding='utf-8')
print('✓ Updated all product names to English (RomanUrdu) format')
